import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseResumeYaml, ResumeYamlError } from '../src/resumeSchema.ts'

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const inputPath = resolve(repoRoot, 'resume.yaml')
const outputPath = resolve(repoRoot, 'src/resume.generated.ts')

async function main() {
  const rawYaml = await readFile(inputPath, 'utf8')
  const resume = parseResumeYaml(rawYaml)

  const output = `// This file is generated by scripts/generate-resume.ts.
// Do not edit manually. Change resume.yaml, then run npm run generate:resume.

import type { ResumeData } from './resumeTypes'

export const resume: ResumeData = ${JSON.stringify(resume, null, 2)}
`

  await mkdir(dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output)
  console.log(`Generated ${relative(repoRoot, outputPath)} from ${relative(repoRoot, inputPath)}`)
}

main().catch((error: unknown) => {
  if (error instanceof ResumeYamlError) {
    console.error(`Invalid ${relative(repoRoot, inputPath)}:`)
    for (const issue of error.issues) {
      console.error(`- ${issue}`)
    }
  } else {
    console.error(error instanceof Error ? error.message : String(error))
  }

  process.exit(1)
})
